# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '55814138-12c3-4a65-915f-76fbf2320e92'
  azureSubscription: 'cargo-20volume-20220610'
  appName: 'rafalwebapp'
  containerRegistry: 'rafalregistry.azurecr.io'
  imageRepository: 'webimage'
  dockerfilePath: '$(Build.SourcesDirectory)/dotnet/Dockerfile'
  tag: 'latestt'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildAndPushImage
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        command: buildAndPush
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: $(tag)

- stage: DeployToWebApp
  displayName: 'Deploy to Azure Web App'
  dependsOn: BuildAndPushImage
  condition: succeeded('BuildAndPushImage')
  jobs:
  - job: AppDeployment
    displayName: 'Deploy to Web App'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Azure Web App on Container Deploy'
      inputs:
        azureSubscription: 'ARMconnection'
        appName: $(appName)
        containers: $(containerRegistry)/$(imageRepository):$(tag)